---
apiVersion: v1
kind: Service
metadata:
  name: covid19-external-golang-service
spec:
  selector:
    app: covid19-external-golang
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort