---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid19-external-golang-deployment-{{ .Chart.Version }}
  labels:
    app: covid19-external-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid19-external-golang
  template:
    metadata:
      labels:
        app: covid19-external-golang
    spec:
      containers:
        - name: covid19-external-golang
          image: denisduev/covid19-external-golang:{{ .Values.imageExternalVersion }}
          ports:
            - containerPort: 8080
          env:
            - name: EXTERNAL_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: external-api-key
                  key: apiKey