---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: covid19-ingress
spec:
  rules:
    - host: my.covid19.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: covid19-service-frontend
                port:
                  number: 80
          - path: /news
            pathType: Prefix
            backend:
              service:
                name: spring-boot
                port:
                  number: 8081