---
apiVersion: v1
kind: Service
metadata:
  name: covid19-stats-service
spec:
  selector:
    app: covid19-asp-net
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: NodePort